export enum ActionTypes {
  SET_MATRIX_DIMENSIONS = 'WORLD/SET_MATRIX_DIMENSIONS',
  SET_MATRIX = 'WORLD/SET_MATRIX',
  SET_ISLANDS = 'WORLD/SET_ISLANDS',
  SET_ACTIVE_CELLS = 'WORLD/SET_ACTIVE_CELLS'
}
